"""empty message

Revision ID: 06cc466fd561
Revises: c28c844058b3
Create Date: 2018-08-11 17:53:32.465277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cc466fd561'
down_revision = 'c28c844058b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control', sa.Column('language', sa.String(length=4), server_default='en', nullable=True))
    op.add_column('control', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control', 'number')
    op.drop_column('control', 'language')
    # ### end Alembic commands ###
