"""empty message

Revision ID: 0f520cd98273
Revises: cccbd24f64bd
Create Date: 2018-08-06 17:56:45.407288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f520cd98273'
down_revision = 'cccbd24f64bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_credential', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_unique_constraint('account_cred_uniq', 'account_credential', ['name', 'owner_id'])
    op.create_index(op.f('ix_account_credential_name'), 'account_credential', ['name'], unique=False)
    op.drop_index('ix_account_credential_username', table_name='account_credential')
    op.create_index(op.f('ix_account_credential_username'), 'account_credential', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_credential_username'), table_name='account_credential')
    op.create_index('ix_account_credential_username', 'account_credential', ['username'], unique=True)
    op.drop_index(op.f('ix_account_credential_name'), table_name='account_credential')
    op.drop_constraint('account_cred_uniq', 'account_credential', type_='unique')
    op.drop_column('account_credential', 'name')
    # ### end Alembic commands ###
