"""empty message

Revision ID: 26778fce2cf1
Revises: 86384f47bc1a
Create Date: 2018-08-05 09:41:28.911221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26778fce2cf1'
down_revision = '86384f47bc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_to_credential')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_to_credential',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scan_profile_id', sa.INTEGER(), nullable=True),
    sa.Column('transport', sa.VARCHAR(), nullable=False),
    sa.Column('credential_id', sa.INTEGER(), nullable=True),
    sa.Column('settings', sa.VARCHAR(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['account_credential.id'], ),
    sa.ForeignKeyConstraint(['scan_profile_id'], ['scan_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
