"""empty message

Revision ID: 3930dc3cfc4a
Revises: 06cc466fd561
Create Date: 2018-08-11 17:59:03.589081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3930dc3cfc4a'
down_revision = '06cc466fd561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_control_language'), 'control', ['language'], unique=False)
    op.create_index(op.f('ix_control_number'), 'control', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_number'), table_name='control')
    op.drop_index(op.f('ix_control_language'), table_name='control')
    # ### end Alembic commands ###
