"""empty message

Revision ID: 3b757cc9ceae
Revises: 0f520cd98273
Create Date: 2018-08-06 20:16:36.559650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '3b757cc9ceae'
down_revision = '0f520cd98273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    task_status = ENUM('Idle', 'Wait', 'Running', name='taskstatus')
    task_status.create(op.get_bind())

    op.add_column('task', sa.Column('status', sa.Enum('Idle', 'Wait', 'Running', name='taskstatus')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'status')
    task_status = ENUM('Idle', 'Wait', 'Running', name='taskstatus')
    task_status.drop(op.get_bind())
    # ### end Alembic commands ###
