"""empty message

Revision ID: 3eb700176c37
Revises: 6561a3ed088e
Create Date: 2018-08-05 09:46:10.720586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb700176c37'
down_revision = '6561a3ed088e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_credential_owner_id'), 'account_credential', ['owner_id'], unique=False)
    op.create_index(op.f('ix_profile_setting_profile_id'), 'profile_setting', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_setting_profile_id'), table_name='profile_setting')
    op.drop_index(op.f('ix_account_credential_owner_id'), table_name='account_credential')
    # ### end Alembic commands ###
