"""empty message

Revision ID: 3f075620571f
Revises: 3eb700176c37
Create Date: 2018-08-05 15:27:56.990245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f075620571f'
down_revision = '3eb700176c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_setting_profile_id_fkey', 'profile_setting', type_='foreignkey')
    op.create_foreign_key('profile_setting_fk', 'profile_setting', 'scan_profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('scan_profile_owner_id_fkey', 'scan_profile', type_='foreignkey')
    op.create_foreign_key('scan_profile_fk', 'scan_profile', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scan_profile_fk', 'scan_profile', type_='foreignkey')
    op.create_foreign_key('scan_profile_owner_id_fkey', 'scan_profile', 'user', ['owner_id'], ['id'])
    op.drop_constraint('profile_setting_fk', 'profile_setting', type_='foreignkey')
    op.create_foreign_key('profile_setting_profile_id_fkey', 'profile_setting', 'scan_profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###
