"""empty message

Revision ID: 6561a3ed088e
Revises: 26778fce2cf1
Create Date: 2018-08-05 09:42:24.078875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6561a3ed088e'
down_revision = '26778fce2cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(), nullable=False),
    sa.Column('setting', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['scan_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_setting')
    # ### end Alembic commands ###
