"""empty message

Revision ID: 81f0fb6d5582
Revises: 3f075620571f
Create Date: 2018-08-05 18:01:16.198675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f0fb6d5582'
down_revision = '3f075620571f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='task_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.create_table('task_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['scan_profile.id'], name='task_setting_fk', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='task_setting_fk2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_setting')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
