"""empty message

Revision ID: 86384f47bc1a
Revises: dc8f254ec681
Create Date: 2018-08-04 21:14:32.759058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86384f47bc1a'
down_revision = 'dc8f254ec681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_to_credential', sa.Column('settings', sa.String(4096), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_to_credential', 'settings')
    # ### end Alembic commands ###
