"""empty message

Revision ID: bd6687dcade8
Revises: 94c05d70fb86
Create Date: 2018-08-12 15:40:16.233384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6687dcade8'
down_revision = '94c05d70fb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_result_fk', 'task_result', type_='foreignkey')
    op.create_foreign_key('task_result_fk', 'task_result', 'task', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_result_fk', 'task_result', type_='foreignkey')
    op.create_foreign_key('task_result_fk', 'task_result', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
