"""empty message

Revision ID: c28c844058b3
Revises: 08859f2750cd
Create Date: 2018-08-11 17:32:04.211392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28c844058b3'
down_revision = '08859f2750cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('control_result', sa.Column('control_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_result', 'control_number')
    op.drop_table('control')
    # ### end Alembic commands ###
