"""empty message

Revision ID: dfd136f30601
Revises: 3b757cc9ceae
Create Date: 2018-08-06 20:36:03.825849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfd136f30601'
down_revision = '3b757cc9ceae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=postgresql.ENUM('Idle', 'Wait', 'Running', name='taskstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=postgresql.ENUM('Idle', 'Wait', 'Running', name='taskstatus'),
               nullable=True)
    # ### end Alembic commands ###
